project:
  type: website

website:
  title: "ImgLib2 and BigDataviewer projects"
  navbar:
    right:
      - href: posts.qmd
        text: Blog
      - href: index.qmd  
        text: Learning Resources
      - href: ecosystem.qmd
        text: Ecosystem  
      - href: index.qmd
        text: Contributing Guidelines
      - about.qmd
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



