project:
  type: website

website:
  title: "ImgLib2 and BigDataviewer projects"
  navbar:
    right:
      - href: posts.qmd
        text: Blog
      - text: Learning Resources  
        menu:
             - text: "ImgLib2 links"
               icon: "info-square"
               href: "index"
             - text: "BigDataViewer links"
               icon: "info-square"
               href: "index"
      - href: ecosystem.qmd
        text: Ecosystem  
      - text: Contributing Guidelines
        menu:
             - text: "Guidelines for ImgLib2"
               icon: "share"
               href: "index.qmd"
             - text: "Guidelines for BigDataViewer"
               icon: "share"
               href: "index.qmd"
             - text: "Our Code-of-conduct"
               icon: "peace"
               href: "index.qmd"
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



